import { Category, Product, Offer, Coupon, SchoolPack, SchoolList, Supplier, StoreSettings, UserProfile } from '../types';

export const INITIAL_SETTINGS: StoreSettings = {
  name: 'BIKIE',
  slogan: 'Todo lo que necesitas para estudiar, trabajar y crear',
  description: 'Papelería, librería, material de oficina, bellas artes y servicios escolares integrales en Malabo / África Central.',
  phone: '+240 222 345 678',
  whatsapp: '+240 555 890 123',
  email: 'contacto@bikie-papeleria.com',
  address: 'Avenida de la Independencia, Edificio Central, Malabo',
  city: 'Malabo',
  opening_hours: 'Lunes a Viernes: 08:00 - 19:30 | Sábados: 09:00 - 15:00',
  currency: 'XAF',
  currency_symbol: 'FCFA',
  logo_url: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=200&auto=format&fit=crop&q=80',
  banner_headline: 'Todo lo que necesitas para estudiar, trabajar y crear.',
  banner_subheadline: 'Descubre nuestro catálogo escolar, de oficina y arte. O sube una foto de tu lista de útiles y nuestra IA prepara tu carrito en segundos.',
  free_shipping_min: 25000,
  points_per_1000_xaf: 10,
  facebook: 'https://facebook.com/bikiepapeleria',
  instagram: 'https://instagram.com/bikiepapeleria',
};

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-escolar',
    name: 'Material escolar',
    slug: 'material-escolar',
    description: 'Todo lo necesario para el colegio, instituto y universidad',
    icon: 'GraduationCap',
    image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=600&auto=format&fit=crop&q=80',
    display_order: 1,
  },
  {
    id: 'cat-oficina',
    name: 'Oficina',
    slug: 'oficina',
    description: 'Suministros profesionales y ergonomía para tu espacio de trabajo',
    icon: 'Briefcase',
    image: 'https://images.unsplash.com/photo-1497032628192-86f99bcd76bc?w=600&auto=format&fit=crop&q=80',
    display_order: 2,
  },
  {
    id: 'cat-escritura',
    name: 'Escritura',
    slug: 'escritura',
    description: 'Bolígrafos, plumas, portaminas, rotuladores y marcadores',
    icon: 'PenTool',
    image: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=600&auto=format&fit=crop&q=80',
    display_order: 3,
  },
  {
    id: 'cat-cuadernos',
    name: 'Cuadernos',
    slug: 'cuadernos',
    description: 'Cuadernos espiral, libretas cosidas, agendas y blocs',
    icon: 'BookOpen',
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
    display_order: 4,
  },
  {
    id: 'cat-carpetas',
    name: 'Carpetas',
    slug: 'carpetas',
    description: 'Archivadores de palanca, fundas, clasificadores y carpetas de anillas',
    icon: 'Folder',
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    display_order: 5,
  },
  {
    id: 'cat-dibujo',
    name: 'Dibujo',
    slug: 'dibujo',
    description: 'Reglas, compases, escuadras, lápices de grafito y blocs de dibujo',
    icon: 'Compass',
    image: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=600&auto=format&fit=crop&q=80',
    display_order: 6,
  },
  {
    id: 'cat-pintura',
    name: 'Pintura',
    slug: 'pintura',
    description: 'Acuarelas, témperas, acrílicos, pinceles y lienzos',
    icon: 'Palette',
    image: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=600&auto=format&fit=crop&q=80',
    display_order: 7,
  },
  {
    id: 'cat-mochilas',
    name: 'Mochilas',
    slug: 'mochilas',
    description: 'Mochilas ergonómicas, estuches y bolsas de merienda',
    icon: 'Backpack',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80',
    display_order: 8,
  },
  {
    id: 'cat-manualidades',
    name: 'Manualidades',
    slug: 'manualidades',
    description: 'Goma EVA, cartulinas, tijeras escolares, purpurina y pegamento',
    icon: 'Scissors',
    image: 'https://images.unsplash.com/photo-1516962215378-7fa2e137ae93?w=600&auto=format&fit=crop&q=80',
    display_order: 9,
  },
  {
    id: 'cat-material-educativo',
    name: 'Material educativo',
    slug: 'material-educativo',
    description: 'Ábacos, mapas, juegos de lógica y recursos didácticos',
    icon: 'Sparkles',
    image: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=600&auto=format&fit=crop&q=80',
    display_order: 10,
  },
  {
    id: 'cat-impresion',
    name: 'Impresión',
    slug: 'impresion',
    description: 'Papel fotocopia A4/A3, cartuchos, tóners y etiquetas',
    icon: 'Printer',
    image: 'https://images.unsplash.com/photo-1589330694653-ded6df03f754?w=600&auto=format&fit=crop&q=80',
    display_order: 11,
  },
  {
    id: 'cat-otros',
    name: 'Otros',
    slug: 'otros',
    description: 'Calculadoras, pilas, adhesivos especiales y accesorios',
    icon: 'Package',
    image: 'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=600&auto=format&fit=crop&q=80',
    display_order: 12,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-01',
    name: 'Cuaderno A4 Espiral Cuadriculado 80 Hojas Oxford',
    slug: 'cuaderno-a4-espiral-cuadriculado-oxford',
    description: 'Cuaderno microperforado de alta calidad con tapa dura extrarresistente. Papel Optik Paper de 90g/m² que no traspasa la tinta.',
    category_id: 'cat-cuadernos',
    category_name: 'Cuadernos',
    brand: 'Oxford',
    sku: 'OXF-A4-80C',
    barcode: '8412345678011',
    purchase_price: 1200,
    sale_price: 2500,
    previous_price: 2800,
    stock: 65,
    min_stock: 15,
    status: 'active',
    is_featured: true,
    is_new: false,
    is_offer: true,
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1517842645767-c639042777db?w=600&auto=format&fit=crop&q=80',
    ],
    tags: ['cuaderno', 'a4', 'cuadriculado', 'oxford', 'escolar', 'papel'],
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'prod-02',
    name: 'Bolígrafo BIC Cristal Azul Punta Media 1.0mm',
    slug: 'boligrafo-bic-cristal-azul-1-0mm',
    description: 'El bolígrafo más vendido del mundo. Cuerpo hexagonal transparente y tinta fluida de secado rápido con duración de hasta 3km de escritura.',
    category_id: 'cat-escritura',
    category_name: 'Escritura',
    brand: 'BIC',
    sku: 'BIC-CRIS-AZ',
    barcode: '8412345678028',
    purchase_price: 150,
    sale_price: 350,
    previous_price: 400,
    stock: 350,
    min_stock: 50,
    status: 'active',
    is_featured: true,
    is_new: false,
    is_offer: false,
    image: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=600&auto=format&fit=crop&q=80',
    ],
    tags: ['boligrafo', 'azul', 'bic', 'cristal', 'boli', 'lapicero', 'escritura'],
    created_at: new Date(Date.now() - 40 * 86400000).toISOString(),
  },
  {
    id: 'prod-03',
    name: 'Bolígrafo BIC Cristal Negro Punta Media 1.0mm',
    slug: 'boligrafo-bic-cristal-negro-1-0mm',
    description: 'Bolígrafo clásico de escritura suave en tinta negra. Punta de bola de carburo de tungsteno perfectamente esférica.',
    category_id: 'cat-escritura',
    category_name: 'Escritura',
    brand: 'BIC',
    sku: 'BIC-CRIS-NG',
    barcode: '8412345678035',
    purchase_price: 150,
    sale_price: 350,
    previous_price: 400,
    stock: 220,
    min_stock: 40,
    status: 'active',
    is_featured: false,
    is_new: false,
    is_offer: false,
    image: 'https://images.unsplash.com/photo-1585336261026-4a9235e1654e?w=600&auto=format&fit=crop&q=80',
    tags: ['boligrafo', 'negro', 'bic', 'cristal', 'boli', 'escritura'],
    created_at: new Date(Date.now() - 40 * 86400000).toISOString(),
  },
  {
    id: 'prod-04',
    name: 'Bolígrafo BIC Cristal Rojo Punta Media 1.0mm',
    slug: 'boligrafo-bic-cristal-rojo-1-0mm',
    description: 'Bolígrafo de tinta roja ideal para correcciones y notas destacadas.',
    category_id: 'cat-escritura',
    category_name: 'Escritura',
    brand: 'BIC',
    sku: 'BIC-CRIS-RJ',
    barcode: '8412345678042',
    purchase_price: 150,
    sale_price: 350,
    previous_price: 400,
    stock: 180,
    min_stock: 30,
    status: 'active',
    is_featured: false,
    is_new: false,
    is_offer: false,
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    tags: ['boligrafo', 'rojo', 'bic', 'cristal', 'boli', 'escritura'],
    created_at: new Date(Date.now() - 40 * 86400000).toISOString(),
  },
  {
    id: 'prod-05',
    name: 'Carpeta A4 de 4 Anillas con Recambio Grafoplas',
    slug: 'carpeta-a4-4-anillas-recambio-grafoplas',
    description: 'Carpeta de anillas de cartón forrado con plastificado soft-touch. Incluye recambio de 100 hojas cuadrícula 5mm y 4 separadores de colores.',
    category_id: 'cat-carpetas',
    category_name: 'Carpetas',
    brand: 'Grafoplas',
    sku: 'GRAF-CARP-A4',
    barcode: '8412345678059',
    purchase_price: 3200,
    sale_price: 6500,
    previous_price: 7200,
    stock: 42,
    min_stock: 10,
    status: 'active',
    is_featured: true,
    is_new: true,
    is_offer: false,
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    tags: ['carpeta', 'anillas', 'a4', 'archivador', 'recambio', 'escolar'],
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
  {
    id: 'prod-06',
    name: 'Regla Técnica Graduada Transparente 30 cm Faber-Castell',
    slug: 'regla-tecnica-transparente-30cm-faber-castell',
    description: 'Regla de plástico transparente biselada de 30 cm con graduación milimétrica nítida indeleble.',
    category_id: 'cat-dibujo',
    category_name: 'Dibujo',
    brand: 'Faber-Castell',
    sku: 'FC-REG-30',
    barcode: '8412345678066',
    purchase_price: 450,
    sale_price: 1200,
    previous_price: 1400,
    stock: 80,
    min_stock: 20,
    status: 'active',
    is_featured: false,
    is_new: false,
    is_offer: false,
    image: 'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=600&auto=format&fit=crop&q=80',
    tags: ['regla', '30cm', 'dibujo', 'faber castell', 'geometria'],
    created_at: new Date(Date.now() - 50 * 86400000).toISOString(),
  },
  {
    id: 'prod-07',
    name: 'Goma de Borrar Milan 430 Clásica',
    slug: 'goma-de-borrar-milan-430-clasica',
    description: 'Goma de miga de pan sintética suave de caucho sintético tipo "miga de pan". Borra limpiamente lápices de grafito sin dañar el papel.',
    category_id: 'cat-escolar',
    category_name: 'Material escolar',
    brand: 'Milan',
    sku: 'MIL-GOM-430',
    barcode: '8412345678073',
    purchase_price: 180,
    sale_price: 450,
    previous_price: 500,
    stock: 240,
    min_stock: 40,
    status: 'active',
    is_featured: false,
    is_new: false,
    is_offer: false,
    image: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=600&auto=format&fit=crop&q=80',
    tags: ['goma', 'borrador', 'milan', '430', 'borrar', 'escolar'],
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
  },
  {
    id: 'prod-08',
    name: 'Caja de 24 Lápices de Colores Faber-Castell Ecolápiz',
    slug: 'caja-24-lapices-colores-faber-castell',
    description: 'Caja con 24 lápices de colores vivos y mina con tecnología de pegado especial SV antirrotura. Madera procedente de bosques sostenibles.',
    category_id: 'cat-pintura',
    category_name: 'Pintura',
    brand: 'Faber-Castell',
    sku: 'FC-COL-24',
    barcode: '8412345678080',
    purchase_price: 3100,
    sale_price: 6500,
    previous_price: 7500,
    stock: 4,
    min_stock: 8,
    status: 'active',
    is_featured: true,
    is_new: false,
    is_offer: true,
    image: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=600&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=600&auto=format&fit=crop&q=80',
    ],
    tags: ['lapices de colores', 'colores', 'faber castell', 'caja de lapices', 'pintar', 'escolar', 'dibujo'],
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
  },
  {
    id: 'prod-09',
    name: 'Tijeras Escolares Punta Redonda 13 cm Maped Sensoft',
    slug: 'tijeras-escolares-punta-redonda-13cm-maped',
    description: 'Tijeras ergonómicas con anillas de tacto suave y hojas de acero inoxidable con punta redondeada para máxima seguridad.',
    category_id: 'cat-manualidades',
    category_name: 'Manualidades',
    brand: 'Maped',
    sku: 'MAP-TIJ-13',
    barcode: '8412345678097',
    purchase_price: 800,
    sale_price: 1800,
    previous_price: 2000,
    stock: 55,
    min_stock: 12,
    status: 'active',
    is_featured: false,
    is_new: false,
    is_offer: false,
    image: 'https://images.unsplash.com/photo-1516962215378-7fa2e137ae93?w=600&auto=format&fit=crop&q=80',
    tags: ['tijeras', 'escolar', 'punta redonda', 'maped', 'manualidades'],
    created_at: new Date(Date.now() - 45 * 86400000).toISOString(),
  },
  {
    id: 'prod-10',
    name: 'Pegamento en Barra Pritt 22g Sin Disolventes',
    slug: 'pegamento-en-barra-pritt-22g',
    description: 'El adhesivo en barra preferido por profesores y padres. 97% ingredientes naturales, lavable a 20°C y fijación instantánea.',
    category_id: 'cat-manualidades',
    category_name: 'Manualidades',
    brand: 'Pritt',
    sku: 'PRT-PEG-22',
    barcode: '8412345678103',
    purchase_price: 650,
    sale_price: 1500,
    previous_price: 1700,
    stock: 95,
    min_stock: 20,
    status: 'active',
    is_featured: false,
    is_new: false,
    is_offer: false,
    image: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=600&auto=format&fit=crop&q=80',
    tags: ['pegamento', 'barra', 'pritt', 'adhesivo', 'cola', 'escolar'],
    created_at: new Date(Date.now() - 50 * 86400000).toISOString(),
  },
  {
    id: 'prod-11',
    name: 'Paquete de 500 Hojas Papel DIN A4 80g Navigator',
    slug: 'papel-fotocopia-a4-80g-navigator-500h',
    description: 'Papel multiusos de blancura premium y alto rendimiento para impresoras láser e inyección. Sin atascos garantizado.',
    category_id: 'cat-impresion',
    category_name: 'Impresión',
    brand: 'Navigator',
    sku: 'NAV-PAP-A4-500',
    barcode: '8412345678110',
    purchase_price: 2800,
    sale_price: 5200,
    previous_price: 5800,
    stock: 140,
    min_stock: 25,
    status: 'active',
    is_featured: true,
    is_new: false,
    is_offer: false,
    image: 'https://images.unsplash.com/photo-1589330694653-ded6df03f754?w=600&auto=format&fit=crop&q=80',
    tags: ['papel', 'a4', 'folios', 'paquete folios', 'navigator', 'impresion', 'oficina'],
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
  },
  {
    id: 'prod-12',
    name: 'Mochila Escolar Ergonómica Reforzada BIKIE Pro 28L',
    slug: 'mochila-escolar-ergonomica-reforzada-bikie-pro',
    description: 'Mochila escolar de alta resistencia con tejido impermeable, base acolchada antigolpes, tirantes anatómicos y compartimento acolchado para portátil/tablet.',
    category_id: 'cat-mochilas',
    category_name: 'Mochilas',
    brand: 'BIKIE Exclusive',
    sku: 'BIK-MOC-28L',
    barcode: '8412345678127',
    purchase_price: 9500,
    sale_price: 19500,
    previous_price: 24000,
    stock: 28,
    min_stock: 5,
    status: 'active',
    is_featured: true,
    is_new: true,
    is_offer: true,
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80',
    gallery: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80',
      'https://images.unsplash.com/photo-1546938576-6e6a64f317cc?w=600&auto=format&fit=crop&q=80',
    ],
    tags: ['mochila', 'bolsa', 'bikie', 'ergonomica', 'escolar'],
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
  },
  {
    id: 'prod-13',
    name: 'Calculadora Científica Casio FX-82SPX II Iberia ClassWiz',
    slug: 'calculadora-cientifica-casio-fx-82spx-ii',
    description: 'Calculadora científica con pantalla de alta resolución y menú en castellano, portugués y catalán. 293 funciones matemáticas para ESO y Bachillerato.',
    category_id: 'cat-otros',
    category_name: 'Otros',
    brand: 'Casio',
    sku: 'CAS-FX82-SPX',
    barcode: '8412345678134',
    purchase_price: 9000,
    sale_price: 16500,
    previous_price: 18000,
    stock: 18,
    min_stock: 5,
    status: 'active',
    is_featured: true,
    is_new: false,
    is_offer: false,
    image: 'https://images.unsplash.com/photo-1594980596870-8aa52a78d8cd?w=600&auto=format&fit=crop&q=80',
    tags: ['calculadora', 'cientifica', 'casio', 'fx82', 'matematicas', 'secundaria', 'bachillerato'],
    created_at: new Date(Date.now() - 35 * 86400000).toISOString(),
  },
  {
    id: 'prod-14',
    name: 'Compás Escolar de Precisión con Adaptador Universal Staedtler Noris',
    slug: 'compas-precision-staedtler-noris',
    description: 'Compás escolar con rueda central de precisión y ajuste rápido. Incluye tubo con minas de recambio y adaptador para rotuladores.',
    category_id: 'cat-dibujo',
    category_name: 'Dibujo',
    brand: 'Staedtler',
    sku: 'ST-COM-NOR',
    barcode: '8412345678141',
    purchase_price: 1800,
    sale_price: 3900,
    previous_price: 4500,
    stock: 35,
    min_stock: 8,
    status: 'active',
    is_featured: false,
    is_new: false,
    is_offer: false,
    image: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=600&auto=format&fit=crop&q=80',
    tags: ['compas', 'staedtler', 'dibujo tecnico', 'precision', 'geometria'],
    created_at: new Date(Date.now() - 40 * 86400000).toISOString(),
  },
  {
    id: 'prod-15',
    name: 'Set de 4 Marcadores Fluorescentes Stabilo Boss Original',
    slug: 'set-4-marcadores-fluorescentes-stabilo-boss',
    description: 'Los subrayadores icónicos con tecnología antisecado de hasta 4 horas destapados. Colores: Amarillo, Verde, Rosa y Naranja.',
    category_id: 'cat-escritura',
    category_name: 'Escritura',
    brand: 'Stabilo',
    sku: 'STB-BOSS-4',
    barcode: '8412345678158',
    purchase_price: 2200,
    sale_price: 4600,
    previous_price: 5200,
    stock: 60,
    min_stock: 15,
    status: 'active',
    is_featured: true,
    is_new: false,
    is_offer: false,
    image: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=600&auto=format&fit=crop&q=80',
    tags: ['subrayadores', 'fluorescentes', 'stabilo', 'boss', 'marcadores', 'colores'],
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'prod-16',
    name: 'Juego de Geometría Escolar 4 Piezas Maped (Regla 20cm, Escuadra, Cartabón, Transportador)',
    slug: 'juego-geometria-escolar-maped-4piezas',
    description: 'Estuche completo con 4 piezas de geometría irrompibles con escalas graduadas de alta visibilidad.',
    category_id: 'cat-dibujo',
    category_name: 'Dibujo',
    brand: 'Maped',
    sku: 'MAP-GEO-4P',
    barcode: '8412345678165',
    purchase_price: 1100,
    sale_price: 2600,
    previous_price: 3000,
    stock: 50,
    min_stock: 12,
    status: 'active',
    is_featured: false,
    is_new: false,
    is_offer: false,
    image: 'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=600&auto=format&fit=crop&q=80',
    tags: ['juego de reglas', 'geometria', 'escuadra', 'cartabon', 'transportador', 'regla'],
    created_at: new Date(Date.now() - 28 * 86400000).toISOString(),
  },
  {
    id: 'prod-17',
    name: 'Caja de 12 Lápices de Grafito HB Staedtler Noris 120',
    slug: 'caja-12-lapices-grafito-hb-staedtler-noris',
    description: 'El lápiz de rayas amarillas y negras por excelencia. Mina HB de alta resistencia a la rotura, fácil de afilar y de borrar.',
    category_id: 'cat-escritura',
    category_name: 'Escritura',
    brand: 'Staedtler',
    sku: 'ST-LAP-HB12',
    barcode: '8412345678172',
    purchase_price: 1900,
    sale_price: 4200,
    previous_price: 4800,
    stock: 75,
    min_stock: 15,
    status: 'active',
    is_featured: false,
    is_new: false,
    is_offer: false,
    image: 'https://images.unsplash.com/photo-1585336261026-4a9235e1654e?w=600&auto=format&fit=crop&q=80',
    tags: ['lapiz', 'lapices', 'grafito', 'hb', 'staedtler', 'escritura'],
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
  },
  {
    id: 'prod-18',
    name: 'Sacapuntas con Depósito Doble Orificio Milan Compact',
    slug: 'sacapuntas-deposito-milan-compact',
    description: 'Sacapuntas de diseño compacto con cuchilla de acero al carbono de seguridad y depósito para virutas.',
    category_id: 'cat-escolar',
    category_name: 'Material escolar',
    brand: 'Milan',
    sku: 'MIL-SAC-COM',
    barcode: '8412345678189',
    purchase_price: 400,
    sale_price: 950,
    previous_price: 1100,
    stock: 110,
    min_stock: 25,
    status: 'active',
    is_featured: false,
    is_new: false,
    is_offer: false,
    image: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=600&auto=format&fit=crop&q=80',
    tags: ['sacapuntas', 'tajalapiz', 'milan', 'deposito', 'escolar'],
    created_at: new Date(Date.now() - 40 * 86400000).toISOString(),
  },
];

export const INITIAL_OFFERS: Offer[] = [
  {
    id: 'off-01',
    name: 'Gran Campaña Vuelta al Cole BIKIE',
    description: 'Descuento especial del 15% en todos los cuadernos Oxford y carpetas de anillas.',
    type: 'percentage',
    discount_value: 15,
    product_ids: ['prod-01', 'prod-05'],
    category_ids: ['cat-cuadernos', 'cat-carpetas'],
    start_date: new Date(Date.now() - 5 * 86400000).toISOString().split('T')[0],
    end_date: new Date(Date.now() + 60 * 86400000).toISOString().split('T')[0],
    status: 'active',
  },
  {
    id: 'off-02',
    name: 'Pack Mochila + Set Geometría',
    description: 'Precio especial combo al comprar mochila BIKIE Pro.',
    type: 'special_price',
    discount_value: 3000,
    product_ids: ['prod-12', 'prod-16'],
    category_ids: ['cat-mochilas'],
    start_date: new Date(Date.now() - 10 * 86400000).toISOString().split('T')[0],
    end_date: new Date(Date.now() + 45 * 86400000).toISOString().split('T')[0],
    status: 'active',
  },
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'coup-01',
    code: 'BIKIE10',
    description: '10% de descuento en tu primera compra online',
    discount_type: 'percent',
    discount_value: 10,
    min_purchase: 5000,
    max_uses: 500,
    uses_count: 34,
    start_date: new Date(Date.now() - 30 * 86400000).toISOString().split('T')[0],
    end_date: new Date(Date.now() + 90 * 86400000).toISOString().split('T')[0],
    is_active: true,
  },
  {
    id: 'coup-02',
    code: 'ESCOLAR2000',
    description: '2.000 XAF de descuento en compras superiores a 30.000 XAF',
    discount_type: 'fixed',
    discount_value: 2000,
    min_purchase: 30000,
    max_uses: 200,
    uses_count: 18,
    start_date: new Date(Date.now() - 10 * 86400000).toISOString().split('T')[0],
    end_date: new Date(Date.now() + 60 * 86400000).toISOString().split('T')[0],
    is_active: true,
  },
];

export const INITIAL_SCHOOL_PACKS: SchoolPack[] = [
  {
    id: 'pack-01',
    name: 'Pack Escolar Primaria Básico',
    description: 'Todo lo indispensable para los primeros cursos de primaria: cuadernos, bolis, goma, sacapuntas, lápices de colores y regla.',
    grade_level: 'Primaria',
    price: 14500,
    original_price: 18200,
    image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=600&auto=format&fit=crop&q=80',
    badge: 'Más Popular',
    items: [
      { product_id: 'prod-01', product_name: 'Cuaderno A4 Oxford (x3)', quantity: 3 },
      { product_id: 'prod-02', product_name: 'Bolígrafo BIC Azul (x2)', quantity: 2 },
      { product_id: 'prod-04', product_name: 'Bolígrafo BIC Rojo (x1)', quantity: 1 },
      { product_id: 'prod-06', product_name: 'Regla 30 cm Faber-Castell', quantity: 1 },
      { product_id: 'prod-07', product_name: 'Goma de Borrar Milan 430', quantity: 2 },
      { product_id: 'prod-08', product_name: 'Caja 24 Lápices Colores Faber', quantity: 1 },
      { product_id: 'prod-10', product_name: 'Pegamento en Barra Pritt', quantity: 1 },
    ],
  },
  {
    id: 'pack-02',
    name: 'Pack Secundaria & Bachillerato Completo',
    description: 'Kit de alto rendimiento para secundaria y bachillerato con calculadora científica, archivador A4, compás y subrayadores.',
    grade_level: 'Secundaria / Bachillerato',
    price: 36900,
    original_price: 43500,
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
    badge: 'Recomendado',
    items: [
      { product_id: 'prod-05', product_name: 'Carpeta A4 4 Anillas Grafoplas', quantity: 1 },
      { product_id: 'prod-13', product_name: 'Calculadora Casio FX-82SPX II', quantity: 1 },
      { product_id: 'prod-14', product_name: 'Compás Precisión Staedtler', quantity: 1 },
      { product_id: 'prod-15', product_name: 'Set 4 Subrayadores Stabilo Boss', quantity: 1 },
      { product_id: 'prod-02', product_name: 'Bolígrafo BIC Azul (x3)', quantity: 3 },
      { product_id: 'prod-03', product_name: 'Bolígrafo BIC Negro (x2)', quantity: 2 },
    ],
  },
];

export const INITIAL_SCHOOL_LISTS: SchoolList[] = [
  {
    id: 'list-01',
    title: 'Lista de Materiales Oficial — 1º a 3º Primaria',
    grade_level: 'Primaria',
    institution: 'Colegio Español & Centros Nacionales',
    description: 'Materiales homologados para el inicio del ciclo de educación primaria.',
    is_published: true,
    items: [
      { product_id: 'prod-01', product_name: 'Cuaderno A4 Oxford Cuadriculado', quantity: 4 },
      { product_id: 'prod-02', product_name: 'Bolígrafo BIC Cristal Azul', quantity: 2 },
      { product_id: 'prod-04', product_name: 'Bolígrafo BIC Cristal Rojo', quantity: 1 },
      { product_id: 'prod-06', product_name: 'Regla 30 cm', quantity: 1 },
      { product_id: 'prod-07', product_name: 'Goma Milan 430', quantity: 2 },
      { product_id: 'prod-08', product_name: 'Lápices de Colores x24', quantity: 1 },
      { product_id: 'prod-09', product_name: 'Tijeras Escolares Maped', quantity: 1 },
      { product_id: 'prod-10', product_name: 'Pegamento Pritt 22g', quantity: 2 },
    ],
  },
  {
    id: 'list-02',
    title: 'Lista de Materiales — 1º a 4º Secundaria (ESO)',
    grade_level: 'Secundaria',
    institution: 'Institutos de Educación Secundaria',
    description: 'Lista estándar con instrumental técnico y carpetas de archivo.',
    is_published: true,
    items: [
      { product_id: 'prod-05', product_name: 'Carpeta A4 4 Anillas con Recambio', quantity: 1 },
      { product_id: 'prod-13', product_name: 'Calculadora Científica Casio FX-82', quantity: 1 },
      { product_id: 'prod-14', product_name: 'Compás Escolar Staedtler Noris', quantity: 1 },
      { product_id: 'prod-15', product_name: 'Marcadores Fluorescentes Stabilo x4', quantity: 1 },
      { product_id: 'prod-11', product_name: 'Paquete de 500 Folios A4 80g Navigator', quantity: 1 },
    ],
  },
  {
    id: 'list-03',
    title: 'Lista de Bellas Artes & Dibujo Técnico',
    grade_level: 'Bachillerato',
    institution: 'Bachillerato de Artes y Arquitectura',
    description: 'Suministros de precisión técnica y plástica.',
    is_published: true,
    items: [
      { product_id: 'prod-14', product_name: 'Compás de Precisión', quantity: 1 },
      { product_id: 'prod-16', product_name: 'Juego de Geometría 4 Piezas Maped', quantity: 1 },
      { product_id: 'prod-08', product_name: 'Lápices de Colores 24 Unidades', quantity: 1 },
      { product_id: 'prod-17', product_name: 'Caja 12 Lápices Grafito HB Staedtler', quantity: 1 },
    ],
  },
];

export const INITIAL_SUPPLIERS: Supplier[] = [
  {
    id: 'sup-01',
    name: 'Distribuidora Ibérica de Papelería S.A.',
    company: 'DIPSA Import-Export',
    phone: '+34 91 555 0192',
    email: 'pedidos@dipsa-papeleria.es',
    address: 'Polígono Industrial Las Mercedes, Madrid, España',
    notes: 'Proveedor principal de marcas Oxford, Milan, BIC y Grafoplas.',
    created_at: new Date(Date.now() - 100 * 86400000).toISOString(),
  },
  {
    id: 'sup-02',
    name: 'Faber-Castell & Staedtler Central Logistics',
    company: 'FC Distribution Africa',
    phone: '+237 670 112 233',
    email: 'contacto@fc-africa-logistics.com',
    address: 'Zona Portuaria de Douala, Camerún',
    notes: 'Suministros de dibujo técnico, lápices de colores y material de precisión.',
    created_at: new Date(Date.now() - 120 * 86400000).toISOString(),
  },
  {
    id: 'sup-03',
    name: 'Navigator & Paper Global Logistics',
    company: 'Navigator Pulp & Paper Int.',
    phone: '+351 21 888 4400',
    email: 'africa.sales@navigator-paper.com',
    address: 'Lisboa, Portugal',
    notes: 'Bobinas y paquetes de folios A4/A3 de alta blancura.',
    created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
  },
];

export const INITIAL_REAL_ADMIN_USER: UserProfile = {
  id: 'usr-tia-admin-01',
  email: 'propietaria@bikie.gq',
  name: 'Propietaria BIKIE (Tía)',
  phone: '+240 222 111 000',
  role: 'admin',
  points: 1500,
  created_at: new Date(Date.now() - 180 * 86400000).toISOString(),
};

export const INITIAL_DEMO_USERS: UserProfile[] = [
  INITIAL_REAL_ADMIN_USER,
];
