import { Category, Product, Offer, Coupon, SchoolPack, SchoolList, Supplier, StoreSettings, UserProfile, ServiceItem, Expense } from '../types';

export const INITIAL_SETTINGS: StoreSettings = {
  name: 'BIKIE',
  slogan: 'Todo lo que necesitas para estudiar, trabajar y crear',
  description: 'Papelería, librería, material escolar, oficina, bellas artes y servicios de copistería e impresión en Malabo, Guinea Ecuatorial.',
  phone: '222213126',
  whatsapp: '222213126',
  email: 'contacto@bikie-papeleria.com',
  address: 'Paraíso, cerca de Banje, Malabo, Guinea Ecuatorial',
  city: 'Malabo',
  opening_hours: 'Lunes a Sábado: 08:00 - 19:30',
  currency: 'XAF',
  currency_symbol: 'FCFA',
  logo_url: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=200&auto=format&fit=crop&q=80',
  banner_headline: 'Todo lo que necesitas para estudiar, trabajar y crear.',
  banner_subheadline: 'Descubre nuestro catálogo escolar, de oficina y arte. O sube una foto de tu lista de útiles y nuestra IA prepara tu carrito en segundos.',
  free_shipping_min: 25000,
  points_per_1000_xaf: 10,
  facebook: 'https://facebook.com/bikiepapeleria',
  instagram: 'https://instagram.com/bikiepapeleria',
};

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-escolar',
    name: 'Material escolar',
    slug: 'material-escolar',
    description: 'Todo lo necesario para el colegio, instituto y universidad',
    icon: 'GraduationCap',
    image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=600&auto=format&fit=crop&q=80',
    display_order: 1,
  },
  {
    id: 'cat-oficina',
    name: 'Oficina',
    slug: 'oficina',
    description: 'Suministros profesionales y consumibles para tu espacio de trabajo',
    icon: 'Briefcase',
    image: 'https://images.unsplash.com/photo-1497032628192-86f99bcd76bc?w=600&auto=format&fit=crop&q=80',
    display_order: 2,
  },
  {
    id: 'cat-escritura',
    name: 'Escritura',
    slug: 'escritura',
    description: 'Bolígrafos, plumas, portaminas, rotuladores y marcadores',
    icon: 'PenTool',
    image: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=600&auto=format&fit=crop&q=80',
    display_order: 3,
  },
  {
    id: 'cat-cuadernos',
    name: 'Cuadernos',
    slug: 'cuadernos',
    description: 'Cuadernos espiral, libretas cosidas, agendas y blocs',
    icon: 'BookOpen',
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
    display_order: 4,
  },
  {
    id: 'cat-carpetas',
    name: 'Carpetas & Archivo',
    slug: 'carpetas',
    description: 'Archivadores de palanca, fundas, clasificadores y carpetas de anillas',
    icon: 'Folder',
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    display_order: 5,
  },
  {
    id: 'cat-dibujo',
    name: 'Dibujo Técnico & Geometría',
    slug: 'dibujo',
    description: 'Reglas, compases, escuadras, lápices de grafito y blocs de dibujo',
    icon: 'Compass',
    image: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=600&auto=format&fit=crop&q=80',
    display_order: 6,
  },
  {
    id: 'cat-pintura',
    name: 'Pintura & Bellas Artes',
    slug: 'pintura',
    description: 'Acuarelas, témperas, acrílicos, pinceles y lienzos',
    icon: 'Palette',
    image: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=600&auto=format&fit=crop&q=80',
    display_order: 7,
  },
  {
    id: 'cat-mochilas',
    name: 'Mochilas & Estuches',
    slug: 'mochilas',
    description: 'Mochilas ergonómicas, estuches triples y portadocumentos',
    icon: 'Backpack',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&auto=format&fit=crop&q=80',
    display_order: 8,
  },
  {
    id: 'cat-papel',
    name: 'Papel & Cartulinas',
    slug: 'papel-cartulinas',
    description: 'Folios multifunción A4/A3, cartulinas de colores y papel charol',
    icon: 'FileText',
    image: 'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=600&auto=format&fit=crop&q=80',
    display_order: 9,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod-01',
    name: 'Cuaderno Espiral Oxford Classic A4 Cuadrícula 4x4 (80 hojas)',
    slug: 'cuaderno-espiral-oxford-classic-a4-cuadricula-80h',
    description: 'Cuaderno escolar espiral tapa extradura con papel OptikPaper de 90g que no traspasa la tinta. Cuadrícula 4x4 con margen. Ideal para primaria, secundaria y universidad.',
    category_id: 'cat-cuadernos',
    category_name: 'Cuadernos',
    brand: 'Oxford',
    sku: 'OXF-A4-80C',
    barcode: '8412345000018',
    purchase_price: 1200,
    sale_price: 2000,
    previous_price: 2500,
    stock: 145,
    min_stock: 20,
    status: 'active',
    is_featured: true,
    is_new: false,
    is_offer: true,
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
    tags: ['cuaderno', 'oxford', 'a4', 'escolar'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-02',
    name: 'Paquete de 500 Folios Navigator Universal A4 80g',
    slug: 'paquete-folios-navigator-universal-a4-80g',
    description: 'Papel multiusos de máxima blancura y suavidad para fotocopiadoras e impresoras láser e inyección de tinta. Cero atascos.',
    category_id: 'cat-papel',
    category_name: 'Papel & Cartulinas',
    brand: 'Navigator',
    sku: 'NAV-A4-500',
    barcode: '5602024000108',
    purchase_price: 3200,
    sale_price: 4500,
    stock: 80,
    min_stock: 15,
    status: 'active',
    is_featured: true,
    image: 'https://images.unsplash.com/photo-1586075010923-2dd4570fb338?w=600&auto=format&fit=crop&q=80',
    tags: ['papel', 'folios', 'a4', 'oficina', 'impresion'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-03',
    name: 'Caja de 50 Bolígrafos BIC Cristal Azul Punta Media 1.0mm',
    slug: 'caja-50-boligrafos-bic-cristal-azul',
    description: 'El bolígrafo clásico más vendido del mundo. Cuerpo transparente, tinta de secado rápido que rinde hasta 3 km de escritura.',
    category_id: 'cat-escritura',
    category_name: 'Escritura',
    brand: 'BIC',
    sku: 'BIC-CRIS-AZ-50',
    barcode: '3086126600234',
    purchase_price: 7000,
    sale_price: 10000,
    stock: 35,
    min_stock: 10,
    status: 'active',
    is_featured: true,
    image: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=600&auto=format&fit=crop&q=80',
    tags: ['bic', 'boligrafo', 'azul', 'escritura'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-04',
    name: 'Bolígrafo BIC Cristal Azul (Unidad Individual)',
    slug: 'boligrafo-bic-cristal-azul-unidad',
    description: 'Bolígrafo clásico BIC punta media 1.0mm color azul para uso diario.',
    category_id: 'cat-escritura',
    category_name: 'Escritura',
    brand: 'BIC',
    sku: 'BIC-CRIS-AZ-U',
    barcode: '3086126600012',
    purchase_price: 150,
    sale_price: 250,
    stock: 320,
    min_stock: 50,
    status: 'active',
    is_featured: false,
    image: 'https://images.unsplash.com/photo-1585336261026-77cc7c5b3096?w=600&auto=format&fit=crop&q=80',
    tags: ['bic', 'boligrafo', 'azul'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-05',
    name: 'Caja de 12 Lápices de Grafito Staedtler Noris HB nº 2',
    slug: 'caja-12-lapices-staedtler-noris-hb2',
    description: 'Lápiz de madera certificada de alta resistencia a la rotura gracias a la formulación de mina superadherida.',
    category_id: 'cat-escritura',
    category_name: 'Escritura',
    brand: 'Staedtler',
    sku: 'STA-NORIS-12',
    barcode: '4007817104033',
    purchase_price: 2200,
    sale_price: 3500,
    stock: 50,
    min_stock: 10,
    status: 'active',
    is_featured: true,
    image: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=600&auto=format&fit=crop&q=80',
    tags: ['lapiz', 'staedtler', 'grafito', 'escolar'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-06',
    name: 'Goma de Borrar Milan 430 Miga de Pan Clásica',
    slug: 'goma-de-borrar-milan-430',
    description: 'Goma de borrar clásica de caucho sintético tipo miga de pan. Borra suavemente sin dañar el papel.',
    category_id: 'cat-escolar',
    category_name: 'Material escolar',
    brand: 'Milan',
    sku: 'MIL-430-U',
    barcode: '8411574043003',
    purchase_price: 150,
    sale_price: 300,
    stock: 190,
    min_stock: 30,
    status: 'active',
    is_featured: false,
    image: 'https://images.unsplash.com/photo-1585336261026-77cc7c5b3096?w=600&auto=format&fit=crop&q=80',
    tags: ['goma', 'milan', 'borrar', 'escolar'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-07',
    name: 'Juego de Reglas y Geometría 4 Piezas Maped Technic',
    slug: 'juego-reglas-geometria-maped-4-piezas',
    description: 'Incluye regla graduada de 30cm, escuadra 45º, cartabón 60º y semicírculo transportador de ángulos de 180º.',
    category_id: 'cat-dibujo',
    category_name: 'Dibujo Técnico & Geometría',
    brand: 'Maped',
    sku: 'MAP-GEOM-4P',
    barcode: '3154142421101',
    purchase_price: 1000,
    sale_price: 1800,
    stock: 65,
    min_stock: 12,
    status: 'active',
    is_featured: true,
    image: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=600&auto=format&fit=crop&q=80',
    tags: ['geometria', 'regla', 'escuadra', 'maped'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-08',
    name: 'Caja de 24 Lápices de Colores Faber-Castell Ecolápiz',
    slug: 'caja-24-lapices-colores-faber-castell',
    description: 'Colores vivos y brillantes de aplicación suave. Madera de manejo forestal sostenible con proceso de pegado especial SV.',
    category_id: 'cat-pintura',
    category_name: 'Pintura & Bellas Artes',
    brand: 'Faber-Castell',
    sku: 'FAB-COL-24',
    barcode: '7891360580226',
    purchase_price: 3500,
    sale_price: 5500,
    previous_price: 6500,
    stock: 42,
    min_stock: 10,
    status: 'active',
    is_featured: true,
    is_offer: true,
    image: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?w=600&auto=format&fit=crop&q=80',
    tags: ['colores', 'faber castell', 'dibujo', 'escolar'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-09',
    name: 'Archivador de Palanca A4 Lomo Ancho 75mm Grafoplás',
    slug: 'archivador-palanca-a4-lomo-ancho-grafoplas',
    description: 'Archivador de cartón forrado con mecanismo de palanca niquelado, cantoneras metálicas y tarjetero en lomo.',
    category_id: 'cat-carpetas',
    category_name: 'Carpetas & Archivo',
    brand: 'Grafoplás',
    sku: 'GRA-ARCH-75',
    barcode: '8414571002231',
    purchase_price: 1800,
    sale_price: 3000,
    stock: 55,
    min_stock: 15,
    status: 'active',
    is_featured: false,
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=600&auto=format&fit=crop&q=80',
    tags: ['archivador', 'oficina', 'palanca', 'carpetas'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-10',
    name: 'Tijera Escolar Milan 13cm con Punta Redonda',
    slug: 'tijera-escolar-milan-13cm',
    description: 'Hojas de acero inoxidable con mango ergonómico simétrico y punta de seguridad para niños.',
    category_id: 'cat-escolar',
    category_name: 'Material escolar',
    brand: 'Milan',
    sku: 'MIL-TIJ-13',
    barcode: '8411574061328',
    purchase_price: 600,
    sale_price: 1200,
    stock: 75,
    min_stock: 15,
    status: 'active',
    is_featured: false,
    image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=600&auto=format&fit=crop&q=80',
    tags: ['tijeras', 'milan', 'escolar'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-11',
    name: 'Pegamento en Barra Pritt 22g Sin Disolventes',
    slug: 'pegamento-barra-pritt-22g',
    description: 'Pegamento en barra limpio, rápido y lavable a 20ºC. 97% ingredientes naturales.',
    category_id: 'cat-escolar',
    category_name: 'Material escolar',
    brand: 'Pritt',
    sku: 'PRI-BAR-22G',
    barcode: '4015000411234',
    purchase_price: 700,
    sale_price: 1500,
    stock: 90,
    min_stock: 20,
    status: 'active',
    is_featured: false,
    image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=600&auto=format&fit=crop&q=80',
    tags: ['pegamento', 'pritt', 'escolar'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'prod-12',
    name: 'Compás Escolar de Precisión con Adaptador Universal',
    slug: 'compas-escolar-precision-adaptador',
    description: 'Compás metálico con rueda central de micro-ajuste y adaptador universal para bolígrafos y rotuladores.',
    category_id: 'cat-dibujo',
    category_name: 'Dibujo Técnico & Geometría',
    brand: 'Maped',
    sku: 'MAP-COMP-UNIV',
    barcode: '3154141975100',
    purchase_price: 1500,
    sale_price: 2800,
    stock: 40,
    min_stock: 10,
    status: 'active',
    is_featured: false,
    image: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=600&auto=format&fit=crop&q=80',
    tags: ['compas', 'dibujo', 'tecnico'],
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_OFFERS: Offer[] = [
  {
    id: 'off-vuelta-cole',
    name: 'Especial Vuelta al Cole BIKIE',
    description: 'Descuento especial en cuadernos Oxford y cajas de colores Faber-Castell.',
    type: 'percentage',
    discount_value: 15,
    product_ids: ['prod-01', 'prod-08'],
    category_ids: ['cat-cuadernos', 'cat-escolar'],
    start_date: new Date().toISOString().split('T')[0],
    end_date: new Date(Date.now() + 60 * 86400000).toISOString().split('T')[0],
    status: 'active',
  },
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'coup-bikie10',
    code: 'BIKIE10',
    description: '10% de descuento en pedidos superiores a 15.000 FCFA',
    discount_type: 'percent',
    discount_value: 10,
    min_purchase: 15000,
    max_uses: 500,
    uses_count: 12,
    start_date: new Date().toISOString().split('T')[0],
    end_date: new Date(Date.now() + 180 * 86400000).toISOString().split('T')[0],
    is_active: true,
  },
];

export const INITIAL_SCHOOL_PACKS: SchoolPack[] = [
  {
    id: 'pack-primaria-completo',
    name: 'Pack Escolar Primaria BIKIE',
    grade_level: 'Primaria (1º a 6º)',
    description: 'Incluye 5 cuadernos Oxford A4, lápices Staedtler, goma Milan, tijeras, pegamento Pritt, colores Faber-Castell y estuche.',
    price: 18500,
    original_price: 22000,
    image: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=600&auto=format&fit=crop&q=80',
    badge: 'MÁS POPULAR',
    items: [
      { product_id: 'prod-01', product_name: 'Cuaderno Espiral Oxford Classic A4', quantity: 5 },
      { product_id: 'prod-05', product_name: 'Caja 12 Lápices Staedtler HB', quantity: 1 },
      { product_id: 'prod-06', product_name: 'Goma de Borrar Milan 430', quantity: 2 },
      { product_id: 'prod-08', product_name: 'Caja 24 Lápices de Colores Faber-Castell', quantity: 1 },
      { product_id: 'prod-10', product_name: 'Tijera Escolar Milan 13cm', quantity: 1 },
      { product_id: 'prod-11', product_name: 'Pegamento en Barra Pritt 22g', quantity: 2 },
    ],
  },
  {
    id: 'pack-secundaria-bachillerato',
    name: 'Pack Secundaria & Bachillerato BIKIE',
    grade_level: 'Secundaria & Bachillerato',
    description: 'Preparado para el curso avanzado: 6 cuadernos Oxford, juego de geometría Maped, compás técnico, bolígrafos BIC y archivador Grafoplás.',
    price: 24500,
    original_price: 28900,
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
    badge: 'COMPLETO',
    items: [
      { product_id: 'prod-01', product_name: 'Cuaderno Espiral Oxford Classic A4', quantity: 6 },
      { product_id: 'prod-07', product_name: 'Juego de Geometría 4 Piezas Maped', quantity: 1 },
      { product_id: 'prod-12', product_name: 'Compás Escolar de Precisión Maped', quantity: 1 },
      { product_id: 'prod-03', product_name: 'Caja de 50 Bolígrafos BIC Azul', quantity: 1 },
      { product_id: 'prod-09', product_name: 'Archivador de Palanca A4 Grafoplás', quantity: 2 },
    ],
  },
];

export const INITIAL_SCHOOL_LISTS: SchoolList[] = [
  {
    id: 'list-colegio-espanol-malabo',
    title: 'Lista Oficial 1º y 2º Primaria — Colegio Español de Malabo',
    grade_level: 'Primaria',
    institution: 'Colegio Español de Malabo',
    description: 'Material escolar homologado según currículo oficial.',
    is_published: true,
    items: [
      { product_id: 'prod-01', product_name: 'Cuadernos Oxford A4 Cuadrícula', quantity: 4 },
      { product_id: 'prod-05', product_name: 'Lápices Staedtler HB nº2', quantity: 2 },
      { product_id: 'prod-06', product_name: 'Goma de Borrar Milan 430', quantity: 2 },
      { product_id: 'prod-08', product_name: 'Lápices de Colores 24 Faber-Castell', quantity: 1 },
      { product_id: 'prod-10', product_name: 'Tijeras Escolares Milan', quantity: 1 },
      { product_id: 'prod-11', product_name: 'Pegamento en Barra Pritt', quantity: 2 },
    ],
  },
];

export const INITIAL_SUPPLIERS: Supplier[] = [
  {
    id: 'sup-01',
    name: 'Distribuidora Ibérica de Papelería S.A.',
    company: 'DIPSA Import-Export',
    phone: '+34 91 555 0192',
    email: 'pedidos@dipsa-papeleria.es',
    address: 'Polígono Industrial Las Mercedes, Madrid, España',
    website: 'https://www.dipsa-papeleria.es',
    notes: 'Proveedor de marcas Oxford, Milan, BIC y Grafoplás.',
    created_at: new Date().toISOString(),
  },
  {
    id: 'sup-02',
    name: 'Navigator Paper Global Logistics',
    company: 'Navigator Pulp & Paper Int.',
    phone: '+351 21 888 4400',
    email: 'africa.sales@navigator-paper.com',
    address: 'Lisboa, Portugal',
    website: 'https://www.thenavigatorcompany.com',
    notes: 'Bobinas y paquetes de folios A4/A3 de alta blancura.',
    created_at: new Date().toISOString(),
  },
];

export const INITIAL_SERVICES: ServiceItem[] = [
  // COPIAS & FOTOCOPIAS
  { id: 'srv-cop-bn', category: 'copies', name: 'Fotocopia B/N A4', price: 50, unit: 'página', icon: 'FileText', is_active: true, created_at: new Date().toISOString() },
  { id: 'srv-cop-color', category: 'copies', name: 'Fotocopia Color A4', price: 150, unit: 'página', icon: 'FileText', is_active: true, created_at: new Date().toISOString() },
  { id: 'srv-cop-a3-bn', category: 'copies', name: 'Fotocopia B/N A3', price: 150, unit: 'página', icon: 'FileText', is_active: true, created_at: new Date().toISOString() },
  { id: 'srv-cop-a3-color', category: 'copies', name: 'Fotocopia Color A3', price: 350, unit: 'página', icon: 'FileText', is_active: true, created_at: new Date().toISOString() },
  { id: 'srv-plast-a4', category: 'copies', name: 'Plastificado A4', price: 500, unit: 'unidad', icon: 'Layers', is_active: true, created_at: new Date().toISOString() },
  { id: 'srv-plast-dni', category: 'copies', name: 'Plastificado Carnet/DNI', price: 300, unit: 'unidad', icon: 'Layers', is_active: true, created_at: new Date().toISOString() },
  { id: 'srv-encuad-esp', category: 'copies', name: 'Encuadernación Espiral', price: 1000, unit: 'cuaderno', icon: 'Scissors', is_active: true, created_at: new Date().toISOString() },

  // REDACCIÓN DE DOCUMENTOS
  { id: 'srv-red-instancia', category: 'documents', name: 'Redacción de Instancia / Carta Oficial', price: 1500, unit: 'doc', icon: 'Edit3', is_active: true, created_at: new Date().toISOString() },
  { id: 'srv-red-cv', category: 'documents', name: 'Redacción y Maquetación de CV', price: 3000, unit: 'doc', icon: 'Edit3', is_active: true, created_at: new Date().toISOString() },
  { id: 'srv-red-contrato', category: 'documents', name: 'Redacción de Contrato (Alquiler/Venta)', price: 5000, unit: 'doc', icon: 'FileCheck', is_active: true, created_at: new Date().toISOString() },
  { id: 'srv-escaneo', category: 'documents', name: 'Escaneo de Documentos a PDF', price: 200, unit: 'página', icon: 'FileText', is_active: true, created_at: new Date().toISOString() },

  // IMPRESIÓN DIGITAL
  { id: 'srv-imp-bn', category: 'printing', name: 'Impresión Documento B/N', price: 100, unit: 'página', icon: 'Printer', is_active: true, created_at: new Date().toISOString() },
  { id: 'srv-imp-color', category: 'printing', name: 'Impresión Documento Color', price: 250, unit: 'página', icon: 'Printer', is_active: true, created_at: new Date().toISOString() },
  { id: 'srv-imp-foto-1015', category: 'printing', name: 'Impresión Foto Brillante 10x15', price: 1000, unit: 'foto', icon: 'Printer', is_active: true, created_at: new Date().toISOString() },
  { id: 'srv-imp-memoria', category: 'printing', name: 'Impresión Tesis / Memoria Completa', price: 7500, unit: 'unidad', icon: 'Printer', is_active: true, created_at: new Date().toISOString() },

  // ZUMOS & BEBIDAS NATURALES
  { id: 'srv-zumo-naranja', category: 'juices', name: 'Zumo Natural de Naranja Exprimida', price: 1000, unit: 'vaso', icon: 'Coffee', is_active: true, created_at: new Date().toISOString() },
  { id: 'srv-zumo-pina', category: 'juices', name: 'Zumo Natural de Piña de Malabo', price: 1200, unit: 'vaso', icon: 'Coffee', is_active: true, created_at: new Date().toISOString() },
  { id: 'srv-agua-50cl', category: 'juices', name: 'Agua Mineral Fría 50cl', price: 500, unit: 'botella', icon: 'Coffee', is_active: true, created_at: new Date().toISOString() },
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 'exp-01',
    concept: 'Pago Alquiler Local Comercial Paraíso',
    category: 'rent',
    amount: 150000,
    date: new Date().toISOString().split('T')[0],
    beneficiary: 'Inmobiliaria Paraíso Malabo',
    payment_method: 'transfer',
    registered_by: 'María Lidia (Propietaria)',
    notes: 'Mensualidad del local de papelería en Paraíso',
    created_at: new Date().toISOString(),
  },
  {
    id: 'exp-02',
    concept: 'Factura Electricidad y Climatización',
    category: 'utilities',
    amount: 35000,
    date: new Date().toISOString().split('T')[0],
    beneficiary: 'SEGESA Malabo',
    payment_method: 'cash',
    registered_by: 'María Lidia (Propietaria)',
    notes: 'Suministro eléctrico del mes',
    created_at: new Date().toISOString(),
  },
];

// ONLY ONE SINGLE USER: THE OWNER / ADMINISTRATOR (MARÍA LIDIA)
export const INITIAL_REAL_ADMIN_USER: UserProfile = {
  id: 'usr-marialidia-01',
  email: 'marialidia@bikie.gq',
  name: 'María Lidia (Propietaria BIKIE)',
  phone: '+240 222 213 126',
  role: 'admin',
  points: 2500,
  created_at: new Date(Date.now() - 180 * 86400000).toISOString(),
};

export const INITIAL_USERS: UserProfile[] = [
  INITIAL_REAL_ADMIN_USER,
];
